use crate::common::{DirGuard, git_add_and_commit, git_cmd, setup_git_repo};
use ledgerful::commands::scan::execute_scan;
use ledgerful::state::layout::Layout;
use ledgerful::state::reports::{ImpactFreshness, check_impact_freshness};
use std::fs;
use tempfile::tempdir;

#[test]
#[allow(non_snake_case)]
fn test_impact_freshness_states__slow() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();

    setup_git_repo(root);
    fs::write(root.join("file1.rs"), "fn one() {}").unwrap();
    git_add_and_commit(root, "initial");

    let _guard = DirGuard::new(root);
    ledgerful::commands::init::execute_init(false, false).unwrap();

    // Commit the .gitignore generated by init so the tree is clean
    git_cmd(root, &["add", "-A"]);
    git_cmd(root, &["commit", "--no-verify", "-m", "commit gitignore"]);

    let layout = Layout::new(root.to_str().unwrap());

    // 1. Missing
    let repo = ledgerful::git::repo::open_repo(root).unwrap();
    let (head_hash, branch_name) = ledgerful::git::repo::get_head_info(&repo).unwrap();
    let snapshot = ledgerful::git::RepoSnapshot {
        head_hash: head_hash.clone(),
        branch_name: branch_name.clone(),
        is_clean: true,
        changes: vec![],
    };

    assert_eq!(
        check_impact_freshness(&layout, &snapshot),
        ImpactFreshness::Missing
    );

    // 2. CurrentClean
    // Run scan --impact on clean tree
    execute_scan(true, false, false, None, None).unwrap();
    assert_eq!(
        check_impact_freshness(&layout, &snapshot),
        ImpactFreshness::CurrentClean
    );

    // 3. CurrentDirty
    // Modify a file to make it dirty
    fs::write(root.join("file1.rs"), "fn one() { println!(); }").unwrap();
    let dirty_snapshot = ledgerful::git::RepoSnapshot {
        head_hash: head_hash.clone(),
        branch_name: branch_name.clone(),
        is_clean: false,
        changes: vec![ledgerful::git::FileChange {
            path: std::path::PathBuf::from("file1.rs"),
            change_type: ledgerful::git::ChangeType::Modified,
            is_staged: false,
        }],
    };
    // Re-scan should yield CurrentDirty
    execute_scan(true, false, false, None, None).unwrap();
    assert_eq!(
        check_impact_freshness(&layout, &dirty_snapshot),
        ImpactFreshness::CurrentDirty
    );

    // 4. Stale (Dirty working tree but scan was clean)
    // Run scan, then modify a file
    git_cmd(root, &["add", "-A"]);
    git_cmd(root, &["commit", "--no-verify", "-m", "second"]);
    execute_scan(true, false, false, None, None).unwrap();

    let (new_head, new_branch) = ledgerful::git::repo::get_head_info(&repo).unwrap();
    fs::write(
        root.join("file1.rs"),
        "fn one() { println!(); println!(); }",
    )
    .unwrap();
    let new_dirty_snapshot = ledgerful::git::RepoSnapshot {
        head_hash: new_head.clone(),
        branch_name: new_branch.clone(),
        is_clean: false,
        changes: vec![ledgerful::git::FileChange {
            path: std::path::PathBuf::from("file1.rs"),
            change_type: ledgerful::git::ChangeType::Modified,
            is_staged: false,
        }],
    };
    let freshness = check_impact_freshness(&layout, &new_dirty_snapshot);
    match freshness {
        ImpactFreshness::Stale { reason } => {
            assert!(reason.contains("Working tree is dirty but impact scan was clean"))
        }
        _ => panic!("Expected stale, got {:?}", freshness),
    }

    // 5. Stale (HEAD changed)
    // Run scan, then commit
    execute_scan(true, false, false, None, None).unwrap(); // CurrentDirty
    git_cmd(root, &["add", "-A"]);
    git_cmd(root, &["commit", "--no-verify", "-m", "third"]);
    let (third_head, third_branch) = ledgerful::git::repo::get_head_info(&repo).unwrap();
    let clean_snapshot = ledgerful::git::RepoSnapshot {
        head_hash: third_head.clone(),
        branch_name: third_branch.clone(),
        is_clean: true,
        changes: vec![],
    };
    let freshness2 = check_impact_freshness(&layout, &clean_snapshot);
    match freshness2 {
        ImpactFreshness::Stale { reason } => assert!(reason.contains("HEAD has changed")),
        _ => panic!("Expected stale, got {:?}", freshness2),
    }
}
