//! Track DX1 — interactive-surface bootstrapping templates.
//!
//! Pure generators and write helpers for the Cedar policy and OpenSLO SLO
//! scaffolds offered when a command surface hits an empty state due to missing
//! prerequisites (`security boundaries` with no Cedar policy data but detected
//! routes; `observability coverage` with no OpenSLO definitions).
//!
//! The generators are deterministic (input sorted before emission) and pure —
//! no I/O, no env, no panics. The write helpers create the target user project
//! directory (`policies/` or `observability/`) relative to the supplied repo
//! root and return the written path. Neither helper touches `.ledgerful/`
//! state; these are user project directories surfaced only on an explicit
//! interactive `[Y/n]` confirmation.

use camino::{Utf8Path, Utf8PathBuf};
use miette::{IntoDiagnostic, Result};

/// Header prepended to every generated Cedar template, explaining provenance
/// and the one next step (`ledgerful index --analyze-graph`).
const CEDAR_HEADER: &str = "\
// Generated by `ledgerful security boundaries` — permissive boilerplate.\n\
// Edit each permit to scope `principal`/`resource`, or convert to `forbid`.\n\
// Re-run `ledgerful index --analyze-graph` after editing to populate this surface.\n";

/// The base OpenSLO v1 SLO template (Track DX1 Part B). Returned verbatim by
/// [`generate_openslo_template`]; the user edits service/metric fields after
/// generation.
///
/// Structured to round-trip through the repo's own `parse_openslo`
/// (`src/observability/openslo.rs`): `indicator` sits directly under `spec`
/// (no nested `indicator.metadata`/`indicator.spec`), `ratioMetric.good` and
/// `ratioMetric.total` are `OpenSloMetric` values with a DIRECT `metricQuery`
/// string and a `metricSource` that carries only `metricSourceRef` + `type`
/// (no `spec.query`), and `alertPolicies` is a list of STRING refs (not
/// structured AlertPolicy/AlertCondition objects). serde ignores unknown
/// fields (`objectives`/`timeWindow`/`budgetingMethod`) which are kept as
/// valid OpenSLO extras for the user but are NOT parsed into the graph.
///
/// NOTE: this MUST be a raw string literal. Rust's `\`-line-continuation in a
/// regular string literal strips leading whitespace on the continued line,
/// which would flatten the YAML indentation and break nested-mapping parsing
/// — exactly the parser-contract failure this template was rewritten to fix.
const OPENSLO_TEMPLATE: &str = r#"# Generated by `ledgerful observability coverage` — base OpenSLO v1 SLO template.
# Edit the service name, metric queries, and objective, then re-run
# `ledgerful index --analyze-graph` to populate this surface.
# Alert policy reference: ledgerful-base-burn-rate — Page when burn rate exceeds 2 over 1h.
apiVersion: openslo/v1
kind: SLO
metadata:
  name: ledgerful-base-slo
  displayName: Ledgerful Base SLO
spec:
  service: ledgerful
  indicator:
    ratioMetric:
      good:
        metricQuery: put-your-good-events-query-here
        metricSource:
          metricSourceRef: ledgerful-datasource
          type: prometheus
      total:
        metricQuery: put-your-total-events-query-here
        metricSource:
          metricSourceRef: ledgerful-datasource
          type: prometheus
  objectives:
    - displayName: Total Errors
      target: 0.99
  timeWindow:
    - duration: 1d
      isRolling: true
  budgetingMethod: Occurrences
  alertPolicies:
    - ledgerful-base-burn-rate
"#;

/// Generate a permissive Cedar policy scaffold with one `permit` clause per
/// `(method, path)` route.
///
/// Routes are sorted by `(method, path)` before emission for deterministic
/// output (call twice → identical bytes), and consecutive duplicate
/// `(method, path)` pairs are dropped so the generator never emits two clauses
/// with the same `@id`/action (belt-and-suspenders against callers that bypass
/// `collect_detected_routes`'s SQL `DISTINCT` dedup). Each route gets an `@id("route_<safe_id>")`
/// where `<safe_id>` is derived from `METHOD path` by lowercasing the method,
/// keeping `[A-Za-z0-9]`, replacing every other char (including `/`) with a
/// single `_`, and collapsing consecutive underscores — e.g. `GET /api/users`
/// → `route_get_api_users`. `principal` and `resource` are left bare
/// (permissive; the user narrows them after generation). No schema is emitted:
/// a standalone `.cedar` file is valid for a bootstrap template.
pub(crate) fn generate_cedar_template(routes: &[(String, String)]) -> String {
    let mut sorted: Vec<&(String, String)> = routes.iter().collect();
    sorted.sort_by(|a, b| (a.0.as_str(), a.1.as_str()).cmp(&(b.0.as_str(), b.1.as_str())));

    // Defensive dedup: drop consecutive duplicates by (method, path) so the
    // generator never emits two `@id("route_<id>")` clauses with the same id or
    // two `permit` clauses for the same action. Belt-and-suspenders against any
    // caller that bypasses the `collect_detected_routes` SQL `DISTINCT` dedup.
    sorted.dedup_by(|a, b| a.0 == b.0 && a.1 == b.1);

    let mut out = String::new();
    out.push_str(CEDAR_HEADER);
    for (method, path) in &sorted {
        let safe_id = sanitize_cedar_id(method, path);
        let action_literal = format!("{} {}", method.to_uppercase(), path);
        out.push('\n');
        out.push_str(&format!("@id(\"route_{safe_id}\")\n"));
        out.push_str("permit (\n");
        out.push_str("    principal,\n");
        out.push_str(&format!("    action == Action::\"{action_literal}\",\n"));
        out.push_str("    resource\n");
        out.push_str(");\n");
    }
    out
}

/// Sanitize `METHOD path` into a Cedar-id-safe identifier: keep `[A-Za-z0-9]`,
/// replace every other character (including `/`, spaces, punctuation) with a
/// single `_`, collapsing runs of underscores and trimming a trailing one.
fn sanitize_cedar_id(method: &str, path: &str) -> String {
    let raw = format!("{}_{}", method.to_lowercase(), path);
    let mut out = String::with_capacity(raw.len());
    let mut prev_under = false;
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
            prev_under = false;
        } else if !prev_under && !out.is_empty() {
            out.push('_');
            prev_under = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    out
}

/// Generate the base OpenSLO v1 SLO template. Pure: returns the constant
/// template verbatim (the user edits service/metric fields after generation).
pub(crate) fn generate_openslo_template() -> String {
    OPENSLO_TEMPLATE.to_string()
}

/// Generate a Cedar template for the supplied routes and write it to
/// `<root>/policies/ledgerful-template.cedar`, creating the `policies/`
/// directory if it does not already exist. Returns the written path.
pub(crate) fn write_cedar_template(
    root: &Utf8Path,
    routes: &[(String, String)],
) -> Result<Utf8PathBuf> {
    let dir = root.join("policies");
    std::fs::create_dir_all(&dir).into_diagnostic()?;
    let path = dir.join("ledgerful-template.cedar");
    std::fs::write(path.as_str(), generate_cedar_template(routes)).into_diagnostic()?;
    Ok(path)
}

/// Generate the base OpenSLO SLO template and write it to
/// `<root>/observability/ledgerful-slo-template.yaml`, creating the
/// `observability/` directory if it does not already exist. Returns the
/// written path.
pub(crate) fn write_openslo_template(root: &Utf8Path) -> Result<Utf8PathBuf> {
    let dir = root.join("observability");
    std::fs::create_dir_all(&dir).into_diagnostic()?;
    let path = dir.join("ledgerful-slo-template.yaml");
    std::fs::write(path.as_str(), generate_openslo_template()).into_diagnostic()?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use camino::Utf8Path;
    use tempfile::tempdir;

    // --- Cedar generator purity + determinism ---

    #[test]
    fn cedar_template_contains_expected_clauses() {
        let routes = vec![
            ("GET".to_string(), "/api/users".to_string()),
            ("POST".to_string(), "/api/users".to_string()),
        ];
        let out = generate_cedar_template(&routes);
        assert!(out.contains("permit"), "expected a permit clause: {out}");
        assert!(
            out.contains("action == Action::\"GET /api/users\""),
            "expected GET action literal: {out}"
        );
        assert!(
            out.contains("action == Action::\"POST /api/users\""),
            "expected POST action literal: {out}"
        );
        assert!(
            out.contains("@id(\"route_get_api_users\")"),
            "expected sanitized route id: {out}"
        );
        assert!(out.contains("principal"), "expected bare principal: {out}");
        assert!(out.contains("resource"), "expected bare resource: {out}");
        assert!(
            out.contains("Generated by `ledgerful security boundaries`"),
            "expected header comment: {out}"
        );
    }

    #[test]
    fn cedar_template_is_deterministic_and_sorted() {
        let routes = vec![
            ("POST".to_string(), "/api/users".to_string()),
            ("GET".to_string(), "/api/users".to_string()),
        ];
        let a = generate_cedar_template(&routes);
        let b = generate_cedar_template(&routes);
        assert_eq!(a, b, "generator must be deterministic");

        // GET must precede POST (sorted by (method, path)).
        let get_pos = a.find("GET /api/users").unwrap();
        let post_pos = a.find("POST /api/users").unwrap();
        assert!(get_pos < post_pos, "routes must be sorted in output: {a}");
    }

    #[test]
    fn cedar_template_sanitizes_unsafe_characters() {
        // Space and braces are not in [A-Za-z0-9_]; they collapse to a single _.
        let routes = vec![("GET".to_string(), "/items/{item_id}".to_string())];
        let out = generate_cedar_template(&routes);
        // Method GET lowercase + path with braces → only [A-Za-z0-9_] in the id.
        assert!(
            out.contains("@id(\"route_get_items_item_id\")"),
            "expected braces and slashes collapsed to underscores: {out}"
        );
        // The action literal preserves the raw path, including braces.
        assert!(
            out.contains("action == Action::\"GET /items/{item_id}\""),
            "action literal must preserve the raw path: {out}"
        );
    }

    #[test]
    fn cedar_template_empty_routes_is_just_header() {
        let out = generate_cedar_template(&[]);
        assert!(
            out.contains("Generated by `ledgerful security boundaries`"),
            "header must still be present: {out}"
        );
        // No routes → no permit clauses. The header text mentions "permit"
        // colloquially ("Edit each permit to scope..."), so check for the
        // structural `permit (` block start rather than the bare word.
        assert!(
            !out.contains("permit ("),
            "no routes → no permit clauses: {out}"
        );
        assert!(
            !out.contains("@id(\"route_"),
            "no routes → no @id clauses: {out}"
        );
    }

    // --- Cedar generator dedup (Finding 3) ---
    //
    // The `api_routes` schema does not enforce uniqueness on
    // `(method, path_pattern)`, so duplicate rows would otherwise produce
    // duplicate `@id("route_<safe_id>")` and duplicate `permit` clauses in the
    // emitted Cedar. `generate_cedar_template` must dedup by `(method, path)`.

    #[test]
    fn cedar_template_dedups_duplicate_routes() {
        let routes = vec![
            ("GET".to_string(), "/api/users".to_string()),
            ("GET".to_string(), "/api/users".to_string()),
            ("POST".to_string(), "/api/users".to_string()),
            ("GET".to_string(), "/api/users".to_string()),
        ];
        let out = generate_cedar_template(&routes);

        // Exactly one permit clause per unique (method, path).
        let permit_count = out.matches("permit (").count();
        assert_eq!(
            permit_count, 2,
            "duplicate routes must collapse to one permit each: {out}"
        );

        // Exactly one `@id` per unique route (no duplicate `@id` strings).
        let id_get_count = out.matches("@id(\"route_get_api_users\")").count();
        assert_eq!(
            id_get_count, 1,
            "duplicate GET /api/users must yield exactly one @id: {out}"
        );
        let id_post_count = out.matches("@id(\"route_post_api_users\")").count();
        assert_eq!(
            id_post_count, 1,
            "duplicate POST /api/users must yield exactly one @id: {out}"
        );

        // Exactly one action literal per unique route.
        let action_get_count = out.matches("action == Action::\"GET /api/users\"").count();
        assert_eq!(
            action_get_count, 1,
            "GET /api/users action literal must appear exactly once: {out}"
        );
        let action_post_count = out.matches("action == Action::\"POST /api/users\"").count();
        assert_eq!(
            action_post_count, 1,
            "POST /api/users action literal must appear exactly once: {out}"
        );
    }

    #[test]
    fn cedar_template_dedups_across_method_boundary() {
        // Same path, different methods are distinct routes; duplicates of each
        // must collapse independently.
        let routes = vec![
            ("GET".to_string(), "/items/{item_id}".to_string()),
            ("GET".to_string(), "/items/{item_id}".to_string()),
            ("DELETE".to_string(), "/items/{item_id}".to_string()),
            ("DELETE".to_string(), "/items/{item_id}".to_string()),
            ("DELETE".to_string(), "/items/{item_id}".to_string()),
        ];
        let out = generate_cedar_template(&routes);

        let permit_count = out.matches("permit (").count();
        assert_eq!(
            permit_count, 2,
            "two unique (method, path) routes → two permits: {out}"
        );
        assert_eq!(
            out.matches("@id(\"route_get_items_item_id\")").count(),
            1,
            "one @id for GET /items/{{item_id}}: {out}"
        );
        assert_eq!(
            out.matches("@id(\"route_delete_items_item_id\")").count(),
            1,
            "one @id for DELETE /items/{{item_id}}: {out}"
        );
    }

    // --- OpenSLO generator purity + determinism ---

    #[test]
    fn openslo_template_contains_expected_fields() {
        let out = generate_openslo_template();
        assert!(out.contains("apiVersion: openslo/v1"), "{out}");
        assert!(out.contains("kind: SLO"), "{out}");
        assert!(out.contains("budgetingMethod: Occurrences"), "{out}");
        assert!(out.contains("target: 0.99"), "{out}");

        // Parser-contract fields (must round-trip through `parse_openslo`):
        // `metricQuery` is a DIRECT string field on `good`/`total`, not nested
        // under `metricSource.spec.query`.
        assert!(
            out.contains("metricQuery: put-your-good-events-query-here"),
            "good.metricQuery must be a direct string field: {out}"
        );
        assert!(
            out.contains("metricQuery: put-your-total-events-query-here"),
            "total.metricQuery must be a direct string field: {out}"
        );
        // `metricSource` carries only `metricSourceRef` + `type` (no `spec.query`).
        assert!(
            out.contains("metricSourceRef: ledgerful-datasource"),
            "metricSource must reference the datasource: {out}"
        );
        assert!(
            out.contains("type: prometheus"),
            "metricSource must declare the source type: {out}"
        );
        assert!(
            !out.contains("metricSource.spec.query"),
            "metricSource must NOT nest a spec.query (parser does not read it): {out}"
        );

        // `indicator` is DIRECTLY under `spec` — no `indicator.metadata` or
        // `indicator.spec` nesting.
        assert!(
            out.contains("indicator:\n    ratioMetric:"),
            "ratioMetric must sit directly under spec.indicator: {out}"
        );
        assert!(
            !out.contains("indicator:\n      metadata:"),
            "indicator.metadata block must be absent: {out}"
        );
        assert!(
            !out.contains("indicator:\n      spec:"),
            "indicator.spec nesting must be absent: {out}"
        );

        // `alertPolicies` is a list of STRING refs (not structured
        // AlertPolicy/AlertCondition objects).
        assert!(
            out.contains("alertPolicies:\n    - ledgerful-base-burn-rate"),
            "alertPolicies must be a list of string refs: {out}"
        );
        assert!(
            !out.contains("kind: AlertCondition"),
            "structured AlertCondition objects must be absent: {out}"
        );
        assert!(
            !out.contains("kind: burnrate"),
            "structured burn-rate condition must be absent: {out}"
        );
    }

    #[test]
    fn openslo_template_is_deterministic() {
        assert_eq!(
            generate_openslo_template(),
            generate_openslo_template(),
            "OpenSLO template must be deterministic"
        );
    }

    // --- Write helpers (generate + write + return path), tested against a tempdir ---

    #[test]
    fn write_cedar_template_creates_dir_and_file_matching_generator() {
        let tmp = tempdir().unwrap();
        let root = Utf8Path::from_path(tmp.path()).unwrap();
        let routes = vec![
            ("GET".to_string(), "/api/users".to_string()),
            ("POST".to_string(), "/api/users".to_string()),
        ];

        let written = write_cedar_template(root, &routes).unwrap();
        assert!(written.exists(), "file should exist at {written}");
        // Component-aware suffix check so it holds on both Windows (`\`) and
        // POSIX (`/`) path separators.
        assert!(
            written.ends_with("policies/ledgerful-template.cedar"),
            "expected path under policies/: {written}"
        );
        assert!(
            root.join("policies").exists(),
            "policies/ directory should have been created"
        );

        let on_disk = std::fs::read_to_string(written.as_str()).unwrap();
        assert_eq!(
            on_disk,
            generate_cedar_template(&routes),
            "file content must match the generator"
        );
    }

    #[test]
    fn write_openslo_template_creates_dir_and_file_matching_generator() {
        let tmp = tempdir().unwrap();
        let root = Utf8Path::from_path(tmp.path()).unwrap();

        let written = write_openslo_template(root).unwrap();
        assert!(written.exists(), "file should exist at {written}");
        // Component-aware suffix check so it holds on both Windows (`\`) and
        // POSIX (`/`) path separators.
        assert!(
            written.ends_with("observability/ledgerful-slo-template.yaml"),
            "expected path under observability/: {written}"
        );
        assert!(
            root.join("observability").exists(),
            "observability/ directory should have been created"
        );

        let on_disk = std::fs::read_to_string(written.as_str()).unwrap();
        assert_eq!(
            on_disk,
            generate_openslo_template(),
            "file content must match the generator"
        );
    }
}
