#!/usr/bin/env bash
# Unit matrix for scripts/prepare-release-cut.sh (0104).
# Run from repo root: bash scripts/test-prepare-release-cut.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PREPARE="${SCRIPT_DIR}/prepare-release-cut.sh"
LIB_SRC="${SCRIPT_DIR}/lib/release-changelog.sh"
UNREL_SRC="${SCRIPT_DIR}/changelog-unreleased.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pass=0
fail=0

assert_pass() {
  local name="$1"
  echo "PASS: ${name}"
  pass=$((pass + 1))
}

assert_fail() {
  local name="$1"
  local detail="${2:-}"
  echo "FAIL: ${name}${detail:+ — ${detail}}" >&2
  fail=$((fail + 1))
}

# Build a minimal git fixture that prepare-release-cut.sh can edit.
# Args: fixture_dir  [unreleased_body_block]
# unreleased_body_block is inserted under ## [Unreleased] (default: one real bullet).
make_fixture() {
  local dir="$1"
  local body="${2:-### Added
- real work for the cut
}"
  rm -rf "$dir"
  mkdir -p "$dir/scripts/lib" "$dir/mcp-server" "$dir/.github/workflows"
  # Scripts: copy prepare + deps so relative paths resolve from fixture root.
  cp "$PREPARE" "$dir/scripts/prepare-release-cut.sh"
  cp "$LIB_SRC" "$dir/scripts/lib/release-changelog.sh"
  cp "$UNREL_SRC" "$dir/scripts/changelog-unreleased.sh"
  chmod +x "$dir/scripts/prepare-release-cut.sh" "$dir/scripts/changelog-unreleased.sh"

  cat >"$dir/Cargo.toml" <<'EOF'
[package]
name = "ledgerful"
version = "0.2.3"
edition = "2024"
EOF

  cat >"$dir/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "ledgerful"
version = "0.2.3"
dependencies = [
 "anyhow",
]
EOF

  cat >"$dir/mcp-server/package.json" <<'EOF'
{
  "name": "@ledgerful/mcp-server",
  "version": "0.1.12",
  "ledgerfulEngineTag": "v0.2.3",
  "description": "fixture"
}
EOF

  cat >"$dir/CHANGELOG.md" <<EOF
# Changelog

## [Unreleased]

${body}
## [0.2.3] - 2026-07-29

### Fixed
- older
EOF

  # Decoy under .github/ so a buggy prepare that touches it is visible in git diff.
  echo "name: decoy" >"$dir/.github/workflows/decoy.yml"

  git -C "$dir" init -q
  git -C "$dir" config user.email "test@example.com"
  git -C "$dir" config user.name "prepare-cut-test"
  # Ensure LF so bash scripts and diffs are stable on Windows.
  git -C "$dir" config core.autocrlf false
  git -C "$dir" add -A
  git -C "$dir" commit -q -m "fixture baseline"
}

run_prepare() {
  local dir="$1"
  shift
  # Run from fixture root (prepare cds to SCRIPT_DIR/..).
  (
    cd "$dir"
    bash scripts/prepare-release-cut.sh "$@"
  )
}

# --- 1. empty Unreleased refused ---------------------------------------------
fx1="$TMP/empty"
make_fixture "$fx1" "

"
set +e
out1="$(run_prepare "$fx1" "0.2.4" 2>&1)"
rc1=$?
set -e
if [ "$rc1" -ne 0 ]; then
  assert_pass "empty Unreleased refused (exit ${rc1})"
else
  assert_fail "empty Unreleased refused" "expected non-zero, got 0; out=${out1}"
fi
# No file should have been modified.
if [ -z "$(git -C "$fx1" diff --name-only)" ]; then
  assert_pass "empty Unreleased: no files modified"
else
  assert_fail "empty Unreleased: no files modified" "diff=$(git -C "$fx1" diff --name-only)"
fi

# --- 2. normal cut → four files, correct contents ----------------------------
fx2="$TMP/normal"
make_fixture "$fx2"
# Freeze date for assertion by pre-computing what we expect (UTC).
expect_date="$(date -u +%Y-%m-%d)"
set +e
out2="$(run_prepare "$fx2" "0.2.4" 2>&1)"
rc2=$?
set -e
if [ "$rc2" -eq 0 ]; then
  assert_pass "normal cut exits 0"
else
  assert_fail "normal cut exits 0" "exit ${rc2}; out=${out2}"
fi

diff2="$(git -C "$fx2" diff --name-only | sed 's#\\#/#g' | sort)"
expect2="$(printf '%s\n' "CHANGELOG.md" "Cargo.lock" "Cargo.toml" "mcp-server/package.json" | sort)"
if [ "$diff2" = "$expect2" ]; then
  assert_pass "normal cut: exactly four files"
else
  assert_fail "normal cut: exactly four files" "got:
${diff2}"
fi

if grep -q '^version = "0.2.4"$' "$fx2/Cargo.toml"; then
  assert_pass "normal cut: Cargo.toml version 0.2.4"
else
  assert_fail "normal cut: Cargo.toml version 0.2.4"
fi

if awk '/^name = "ledgerful"$/ {p=1; next} p && /^version = "/ {print; exit}' "$fx2/Cargo.lock" | grep -q '0.2.4'; then
  assert_pass "normal cut: Cargo.lock ledgerful 0.2.4"
else
  assert_fail "normal cut: Cargo.lock ledgerful 0.2.4"
fi

if grep -qE "^## \[0\.2\.4\] - ${expect_date}$" "$fx2/CHANGELOG.md"; then
  assert_pass "normal cut: dated CHANGELOG section"
else
  assert_fail "normal cut: dated CHANGELOG section" "changelog head:
$(head -n 20 "$fx2/CHANGELOG.md")"
fi

if grep -q '^## \[Unreleased\]$' "$fx2/CHANGELOG.md"; then
  # Fresh Unreleased must be empty of content (heading only before dated section).
  # shellcheck source=lib/release-changelog.sh
  source "${SCRIPT_DIR}/lib/release-changelog.sh"
  if ! changelog_section_has_content "Unreleased" "$fx2/CHANGELOG.md"; then
    assert_pass "normal cut: fresh Unreleased is empty"
  else
    assert_fail "normal cut: fresh Unreleased is empty"
  fi
else
  assert_fail "normal cut: fresh Unreleased heading present"
fi

# --- 3. both mcp version and ledgerfulEngineTag changed ----------------------
# (path-count alone cannot see a missed wrapper bump — 0101 DoD-8 / plan step 9)
if grep -q '"ledgerfulEngineTag": "v0.2.4"' "$fx2/mcp-server/package.json"; then
  assert_pass "mcp ledgerfulEngineTag → v0.2.4"
else
  assert_fail "mcp ledgerfulEngineTag → v0.2.4" "pkg:
$(cat "$fx2/mcp-server/package.json")"
fi
if grep -q '"version": "0.1.13"' "$fx2/mcp-server/package.json"; then
  assert_pass "mcp version patch-bumped 0.1.12 → 0.1.13"
else
  assert_fail "mcp version patch-bumped 0.1.12 → 0.1.13" "pkg:
$(cat "$fx2/mcp-server/package.json")"
fi

# --- 4. Unreleased with ### Added + bullet preserved under dated section -----
fx4="$TMP/heading-bullet"
make_fixture "$fx4" "### Added
- preserved bullet under Added
"
set +e
out4="$(run_prepare "$fx4" "0.2.5" 2>&1)"
rc4=$?
set -e
if [ "$rc4" -eq 0 ]; then
  assert_pass "heading+bullet cut exits 0"
else
  assert_fail "heading+bullet cut exits 0" "exit ${rc4}; out=${out4}"
fi

# Body under ## [0.2.5] must still contain ### Added and the bullet.
body4="$(
  # shellcheck source=lib/release-changelog.sh
  source "${SCRIPT_DIR}/lib/release-changelog.sh"
  changelog_section_body "0.2.5" "$fx4/CHANGELOG.md"
)"
if printf '%s\n' "$body4" | grep -q '### Added' \
  && printf '%s\n' "$body4" | grep -q 'preserved bullet under Added'; then
  assert_pass "### Added + bullet preserved under dated section"
else
  assert_fail "### Added + bullet preserved under dated section" "body:
${body4}"
fi

# --- 5. re-run on already-cut tree refused -----------------------------------
# fx2 is already cut to 0.2.4 (Cargo + dated section). Re-run same version must
# refuse (version-not-greater and/or dated-section re-run guard). Commit first.
git -C "$fx2" add -A
git -C "$fx2" commit -q -m "cut 0.2.4"
# Seed Unreleased so empty-guard is not the first refusal (post-cut Unreleased
# is empty; a bare re-run would hit that first).
awk '
  BEGIN { done = 0 }
  !done && /^## \[Unreleased\]$/ {
    print
    print ""
    print "### Fixed"
    print "- accidental second cut attempt"
    print ""
    done = 1
    next
  }
  { print }
' "$fx2/CHANGELOG.md" >"$fx2/CHANGELOG.md.seed"
mv "$fx2/CHANGELOG.md.seed" "$fx2/CHANGELOG.md"
git -C "$fx2" add CHANGELOG.md
git -C "$fx2" commit -q -m "seed unreleased for re-run"

set +e
out5="$(run_prepare "$fx2" "0.2.4" 2>&1)"
rc5=$?
set -e
# Same version after a cut: refuse. Message may be "must be greater" (Cargo already
# at 0.2.4) or "double-cut" / dated section — both are correct re-run protection.
if [ "$rc5" -ne 0 ]; then
  assert_pass "re-run on already-cut tree refused (exit ${rc5})"
else
  assert_fail "re-run on already-cut tree refused" "expected non-zero; out=${out5}"
fi

# 5b. Dated-section guard specifically: Cargo still at 0.2.3, but CHANGELOG
# already has ## [0.2.5] - date (partial/abandoned cut). Refuse double-cut.
fx5b="$TMP/dated-rerun"
make_fixture "$fx5b" "### Added
- should not double-cut
"
# Insert a dated 0.2.5 section without bumping Cargo (simulate partial cut).
awk '
  BEGIN { done = 0 }
  !done && /^## \[Unreleased\]$/ {
    print
    print ""
    print "### Added"
    print "- should not double-cut"
    print ""
    print "## [0.2.5] - 2026-07-28"
    print ""
    print "### Fixed"
    print "- already titled"
    print ""
    done = 1
    next
  }
  { print }
' "$fx5b/CHANGELOG.md" >"$fx5b/CHANGELOG.md.tmp"
mv "$fx5b/CHANGELOG.md.tmp" "$fx5b/CHANGELOG.md"
# Drop the duplicate body that make_fixture put under Unreleased — rewrite cleanly.
cat >"$fx5b/CHANGELOG.md" <<'EOF'
# Changelog

## [Unreleased]

### Added
- should not double-cut

## [0.2.5] - 2026-07-28

### Fixed
- already titled

## [0.2.3] - 2026-07-29

### Fixed
- older
EOF
git -C "$fx5b" add CHANGELOG.md
git -C "$fx5b" commit -q -m "partial cut dated 0.2.5 only"
set +e
out5b="$(run_prepare "$fx5b" "0.2.5" 2>&1)"
rc5b=$?
set -e
if [ "$rc5b" -ne 0 ] && printf '%s' "$out5b" | grep -qi 'double-cut\|already has a dated\|re-run'; then
  assert_pass "dated-section re-run guard refused 0.2.5"
else
  assert_fail "dated-section re-run guard refused 0.2.5" "exit ${rc5b}; out=${out5b}"
fi

# --- 6. path list has no .github/ --------------------------------------------
fx6="$TMP/no-github"
make_fixture "$fx6"
set +e
out6="$(run_prepare "$fx6" "0.2.4" 2>&1)"
rc6=$?
set -e
diff6="$(git -C "$fx6" diff --name-only | sed 's#\\#/#g')"
if [ "$rc6" -eq 0 ] && ! printf '%s\n' "$diff6" | grep -E '(^|/)\.github/' >/dev/null; then
  assert_pass "path list has no .github/"
else
  assert_fail "path list has no .github/" "exit ${rc6}; paths:
${diff6}; out=${out6}"
fi

# Extra: leading v accepted
fx7="$TMP/leading-v"
make_fixture "$fx7"
set +e
out7="$(run_prepare "$fx7" "v0.2.4" 2>&1)"
rc7=$?
set -e
if [ "$rc7" -eq 0 ] && grep -q '^version = "0.2.4"$' "$fx7/Cargo.toml"; then
  assert_pass "leading v stripped (v0.2.4 → 0.2.4)"
else
  assert_fail "leading v stripped" "exit ${rc7}; out=${out7}"
fi

# Extra: version not greater refused
fx8="$TMP/not-greater"
make_fixture "$fx8"
set +e
out8="$(run_prepare "$fx8" "0.2.3" 2>&1)"
rc8=$?
set -e
if [ "$rc8" -ne 0 ]; then
  assert_pass "version not greater than current refused"
else
  assert_fail "version not greater than current refused" "out=${out8}"
fi

echo ""
echo "prepare-release-cut matrix: ${pass} passed, ${fail} failed"
if [ "$fail" -ne 0 ]; then
  exit 1
fi
exit 0
