use crate::index::symbols::{Symbol, SymbolKind};

pub(super) fn is_entrypoint(symbol: &Symbol) -> bool {
    matches!(
        symbol.entrypoint_kind.as_deref(),
        Some("ENTRYPOINT")
            | Some("HANDLER")
            | Some("PUBLIC_API")
            | Some("TEST")
            | Some("FFI")
            | Some("MACRO")
    )
}

/// Standard Rust traits that are often used implicitly (via derive macros, blanket
/// impls, or trait objects) and therefore produce frequent false positives in dead-code
/// analysis.
const STANDARD_TRAIT_NAMES: &[&str] = &[
    "Eq",
    "PartialEq",
    "Ord",
    "PartialOrd",
    "Default",
    "Clone",
    "Copy",
    "Debug",
    "Display",
    "Hash",
    "Send",
    "Sync",
    "Serialize",
    "Deserialize",
    "From",
    "Into",
    "AsRef",
    "AsMut",
    "Iterator",
    "IntoIterator",
    "Error",
    "ToString",
    "Sized",
    "Drop",
];

/// Returns `true` when a symbol is a standard trait implementation that should be
/// suppressed by default (i.e. when `--include-traits` is not set).
///
/// The Rust AST extractor records `impl Eq for MyType {}` as `SymbolKind::Type`
/// with the trait name (`"Eq"`) as the symbol name.  `SymbolKind::Trait` is only
/// used for *definitions* of traits (`trait Eq { … }`), which never appear in user
/// code for stdlib traits.  Checking `SymbolKind::Type` therefore correctly catches
/// explicit trait-impl blocks while leaving user-defined structs with the same name
/// untouched (they carry `SymbolKind::Struct`).
pub(super) fn is_standard_trait(symbol: &Symbol) -> bool {
    matches!(symbol.kind, SymbolKind::Type) && STANDARD_TRAIT_NAMES.contains(&symbol.name.as_str())
}

/// Name-based confidence penalty (-0.20) applied to symbols whose names match
/// common patterns for dynamically dispatched or serialized types.
///
/// Such types are typically invoked through trait objects, serde, or dependency
/// injection frameworks and therefore produce false positives when no static
/// call edges exist.
const NAME_PENALTY_SUFFIXES: &[&str] = &["Provider", "Result", "Chunk", "Record"];
const NAME_PENALTY: f64 = 0.20;

/// Returns the penalty to subtract from a symbol's confidence score based on its name.
pub(super) fn name_penalty(symbol_name: &str) -> f64 {
    for suffix in NAME_PENALTY_SUFFIXES {
        if symbol_name.ends_with(suffix) {
            return NAME_PENALTY;
        }
    }
    0.0
}

/// Standard Rust derive macros whose presence on a struct/enum signals
/// *implicit* consumption — the type is exercised through generated code
/// (serde reflection, Axum extractors, DB layers, `Debug`-formatting in logs,
/// `Clone`/`Copy` in collection plumbing) rather than via any static
/// call-graph edge. Such types therefore produce false positives in dead-code
/// analysis when they have no explicit callers.
///
/// This list mirrors the standard set called out by the DX4 spec. It is a
/// subset of `STANDARD_TRAIT_NAMES` (which also covers trait-object/blanket-
/// impl names like `Send`/`Sync`/`Drop` that don't appear as derives).
const IMPLICIT_USAGE_DERIVED_TRAITS: &[&str] = &[
    // Standard library / serde reflection derives — usage is implicit via
    // generated code (serde reflection, `Debug`-formatting in logs,
    // `Clone`/`Copy` in collection plumbing) rather than via any static
    // call-graph edge.
    "Serialize",
    "Deserialize",
    "Debug",
    "Clone",
    "Copy",
    "Default",
    "PartialEq",
    "Eq",
    "PartialOrd",
    "Ord",
    "Hash",
    // ORM / DB reflection derives — types are consumed only via runtime
    // reflection (sqlx `FromRow`, diesel `Queryable`/`QueryableByName`,
    // sea_orm `FromQueryResult`) with no static call edges, so they produce
    // false positives in dead-code analysis when no explicit callers exist.
    // (codex Finding 1)
    "FromRow",
    "Queryable",
    "QueryableByName",
    "FromQueryResult",
];

/// Confidence penalty (-0.50) applied to `Struct` and `Enum` symbols that
/// carry at least one `#[derive(...)]` trait whose presence signals implicit
/// consumption (see `IMPLICIT_USAGE_DERIVED_TRAITS`).
///
/// This is DISTINCT from `is_standard_trait` (CG-F6): that filter targets
/// *explicit* `impl Trait for T {}` blocks (stored as `SymbolKind::Type` with
/// the trait name), gated by `--include-traits`. DX4 targets the *type
/// definition itself* (`SymbolKind::Struct`/`Enum`) whose derived impls are
/// generated by macros and never appear as static edges. The derive penalty
/// applies regardless of `--include-traits`: that flag governs explicit trait
/// impls, not derive-generated usage of the underlying type.
///
/// A struct with `#[derive(Serialize, Deserialize, Debug)]` and raw confidence
/// 1.0 falls to 0.5, below the default 0.75 threshold, and is suppressed
/// without the user needing to guess whether `--include-traits` is required.
const DERIVE_PENALTY: f64 = 0.50;

/// Returns the derive-based confidence penalty for `symbol`.
///
/// Reads the `derived_traits` metadata key (a deterministic comma-joined
/// string such as `"Debug,Serialize"`) populated by the Rust AST extractor.
/// Returns `0.0` for non-struct/enum symbols or when no implicit-usage
/// derive is present.
pub(super) fn derive_penalty(symbol: &Symbol) -> f64 {
    if !matches!(symbol.kind, SymbolKind::Struct | SymbolKind::Enum) {
        return 0.0;
    }
    let Some(derived) = symbol.metadata.get("derived_traits") else {
        return 0.0;
    };
    let has_implicit = derived
        .split(',')
        .map(|t| t.trim())
        .any(|t| IMPLICIT_USAGE_DERIVED_TRAITS.contains(&t));
    if has_implicit { DERIVE_PENALTY } else { 0.0 }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::index::symbols::{Symbol, SymbolKind};
    use std::collections::BTreeMap;

    fn make_symbol(name: &str, kind: SymbolKind) -> Symbol {
        Symbol {
            name: name.to_string(),
            kind,
            is_public: false,
            cognitive_complexity: None,
            cyclomatic_complexity: None,
            line_start: None,
            line_end: None,
            qualified_name: None,
            byte_start: None,
            byte_end: None,
            entrypoint_kind: None,
            metadata: BTreeMap::new(),
        }
    }

    #[test]
    fn test_is_standard_trait_matches_impl_type_kind() {
        // The Rust extractor stores `impl Debug for MyType {}` as
        // (name="Debug", kind=SymbolKind::Type). These are the symbols that
        // actually appear in the dead-code index for explicit trait impls.
        let eq = make_symbol("Eq", SymbolKind::Type);
        assert!(is_standard_trait(&eq));

        let ord = make_symbol("Ord", SymbolKind::Type);
        assert!(is_standard_trait(&ord));

        let debug = make_symbol("Debug", SymbolKind::Type);
        assert!(is_standard_trait(&debug));

        let serialize = make_symbol("Serialize", SymbolKind::Type);
        assert!(is_standard_trait(&serialize));
    }

    #[test]
    fn test_is_standard_trait_requires_type_kind() {
        // Same name but wrong kind must NOT be filtered — structs named Eq are valid
        // user-defined types and must not be suppressed.
        let eq_struct = make_symbol("Eq", SymbolKind::Struct);
        assert!(!is_standard_trait(&eq_struct));

        let eq_fn = make_symbol("Eq", SymbolKind::Function);
        assert!(!is_standard_trait(&eq_fn));

        // SymbolKind::Trait is used for trait *definitions* (trait Eq { }), which are
        // stdlib-only and never appear in user-code indices — the filter doesn't need
        // to handle them.
        let eq_trait_def = make_symbol("Eq", SymbolKind::Trait);
        assert!(!is_standard_trait(&eq_trait_def));
    }

    #[test]
    fn test_is_standard_trait_user_defined_trait_not_filtered() {
        let custom = make_symbol("MyCustomTrait", SymbolKind::Type);
        assert!(!is_standard_trait(&custom));
    }

    #[test]
    fn test_name_penalty_provider_suffix() {
        assert!((name_penalty("CIPredictorProvider") - NAME_PENALTY).abs() < f64::EPSILON);
        assert!((name_penalty("SomeProvider") - NAME_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_name_penalty_chunk_suffix() {
        assert!((name_penalty("RetrievedChunk") - NAME_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_name_penalty_record_suffix() {
        assert!((name_penalty("BridgeRecord") - NAME_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_name_penalty_result_suffix() {
        assert!((name_penalty("SearchResult") - NAME_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_name_penalty_no_match() {
        assert_eq!(name_penalty("execute_scan"), 0.0);
        assert_eq!(name_penalty("Config"), 0.0);
        assert_eq!(name_penalty("MyStruct"), 0.0);
    }

    fn make_symbol_with_metadata(
        name: &str,
        kind: SymbolKind,
        metadata: Vec<(&str, &str)>,
    ) -> Symbol {
        let mut map = BTreeMap::new();
        for (k, v) in metadata {
            map.insert(k.to_string(), v.to_string());
        }
        Symbol {
            name: name.to_string(),
            kind,
            is_public: false,
            cognitive_complexity: None,
            cyclomatic_complexity: None,
            line_start: None,
            line_end: None,
            qualified_name: None,
            byte_start: None,
            byte_end: None,
            entrypoint_kind: None,
            metadata: map,
        }
    }

    #[test]
    fn test_derive_penalty_struct_with_implicit_derive() {
        let s = make_symbol_with_metadata(
            "User",
            SymbolKind::Struct,
            vec![("derived_traits", "Debug,Deserialize,Serialize")],
        );
        assert!((derive_penalty(&s) - DERIVE_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_derive_penalty_enum_with_implicit_derive() {
        let e = make_symbol_with_metadata(
            "Shape",
            SymbolKind::Enum,
            vec![("derived_traits", "Clone,Copy,Debug")],
        );
        assert!((derive_penalty(&e) - DERIVE_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_derive_penalty_struct_without_derived_traits_key() {
        let s = make_symbol("Plain", SymbolKind::Struct);
        assert_eq!(derive_penalty(&s), 0.0);
    }

    #[test]
    fn test_derive_penalty_struct_with_only_non_implicit_derive() {
        // A custom derive (not in the implicit-usage set) does NOT trigger the
        // penalty — it may have real generated call edges or none; either way
        // we don't have the signal to suppress it.
        let s = make_symbol_with_metadata(
            "Widget",
            SymbolKind::Struct,
            vec![("derived_traits", "MyCustomDerive")],
        );
        assert_eq!(derive_penalty(&s), 0.0);
    }

    #[test]
    fn test_derive_penalty_ignores_non_struct_enum_kinds() {
        // A `SymbolKind::Type` (used for `impl Trait for T`) must NOT get the
        // derive penalty — explicit impls are CG-F6's territory, gated by
        // `--include-traits`.
        let t =
            make_symbol_with_metadata("Foo", SymbolKind::Type, vec![("derived_traits", "Debug")]);
        assert_eq!(derive_penalty(&t), 0.0);

        let f = make_symbol_with_metadata(
            "foo",
            SymbolKind::Function,
            vec![("derived_traits", "Debug")],
        );
        assert_eq!(derive_penalty(&f), 0.0);
    }

    #[test]
    fn test_derive_penalty_mixed_derive_set() {
        // At least one implicit-usage trait in the set is enough.
        let s = make_symbol_with_metadata(
            "X",
            SymbolKind::Struct,
            vec![("derived_traits", "MyCustom,Serialize,Other")],
        );
        assert!((derive_penalty(&s) - DERIVE_PENALTY).abs() < f64::EPSILON);
    }

    #[test]
    fn test_derive_penalty_db_reflection_derives() {
        // DX4 (codex Finding 1): ORM/DB reflection derives — sqlx `FromRow`,
        // diesel `Queryable`/`QueryableByName`, sea_orm `FromQueryResult` —
        // are consumed only via runtime reflection with no static call
        // edges, so each must trigger the derive penalty. The extractor
        // reduces path-qualified derives to their last segment
        // (`sqlx::FromRow` -> `FromRow`), so we assert by final segment.
        for trait_name in ["FromRow", "Queryable", "QueryableByName", "FromQueryResult"] {
            let s = make_symbol_with_metadata(
                "Model",
                SymbolKind::Struct,
                vec![("derived_traits", trait_name)],
            );
            assert!(
                (derive_penalty(&s) - DERIVE_PENALTY).abs() < f64::EPSILON,
                "{trait_name} must trigger the derive penalty"
            );
        }
    }
}
